INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, EMAIL_VERIFIED, MOBILE_VERIFIED, KYC_VERIFIED, AUTHENTICATOR_KEY, CONFIRMATION_TOKEN, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES ('user@bettergold.in', '$2a$10$EbtAn6fz4AfV631rdXOe5e8w6NchSDEpMGgZBxUujQV/EG9Foh0qC', 'user fname', 'user lname', 'user@bettergold.in', 0, 0, 0, 'dsslk33wdf899', 'klsdf9834543dkf895ya', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));
INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, EMAIL_VERIFIED, MOBILE_VERIFIED, KYC_VERIFIED, AUTHENTICATOR_KEY, CONFIRMATION_TOKEN, ENABLED, LAST_PASSWORD_RESET_DATE, USER_CHANNEL) VALUES ('trader@bettergold.in', '$2a$10$EbtAn6fz4AfV631rdXOe5e8w6NchSDEpMGgZBxUujQV/EG9Foh0qC', 'trader fname', 'trader lname', 'trader@bettergold.in', 0, 0, 0, 'dsslk33wdf899', 'klsdf9834543dkf895ya', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'), '5046550b-226f-4dcb-b6da-76b07b542542');
INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, EMAIL_VERIFIED, MOBILE_VERIFIED, KYC_VERIFIED, AUTHENTICATOR_KEY, CONFIRMATION_TOKEN, ENABLED, LAST_PASSWORD_RESET_DATE, USER_CHANNEL) VALUES ('admin@bettergold.in', '$2a$10$EbtAn6fz4AfV631rdXOe5e8w6NchSDEpMGgZBxUujQV/EG9Foh0qC', 'admin fname', 'admin lname', 'admin@bettergold.in', 0, 0, 0, 'dsslk33wdf899', 'klsdf9834543dkf895ya', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'), '92c5c232-eafb-41fb-b41c-49fff05ca592');
INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, EMAIL_VERIFIED, MOBILE_VERIFIED, KYC_VERIFIED, AUTHENTICATOR_KEY, CONFIRMATION_TOKEN, ENABLED, LAST_PASSWORD_RESET_DATE) VALUES ('disabled@bettergold.in', '$2a$10$EbtAn6fz4AfV631rdXOe5e8w6NchSDEpMGgZBxUujQV/EG9Foh0qC', 'disabled fname', 'disabled lname', 'disabled@bettergold.in', 0, 0, 0, 'dsslk33wdf899', 'klsdf9834543dkf895ya', 0, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_TRADER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (3, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 3);

INSERT INTO PAIR (SYMBOL, BASE_CURRENCY, QUOTE_CURRENCY) VALUES ('BTCINR','BTC', 'INR');
INSERT INTO PAIR (SYMBOL, BASE_CURRENCY, QUOTE_CURRENCY) VALUES ('ETHINR','ETH', 'INR');
INSERT INTO PAIR (SYMBOL, BASE_CURRENCY, QUOTE_CURRENCY) VALUES ('XRPINR','XRP', 'INR');
INSERT INTO PAIR (SYMBOL, BASE_CURRENCY, QUOTE_CURRENCY) VALUES ('ETHBTC','ETH', 'BTC');

INSERT INTO BALANCE (USERNAME, INR, BTC, ETH, XRP, LAST_MODIFIED) VALUES ('admin@bettergold.in', 520003650.20,400000.25487545,15.25,5000.75,CURRENT_TIMESTAMP());
INSERT INTO BALANCE (USERNAME, INR, BTC, ETH, XRP, LAST_MODIFIED) VALUES ('trader@bettergold.in', 520003650.20,400000.25487545,15.25,5000.75,CURRENT_TIMESTAMP());
